[tox]
envlist =
    py310-django{42,52},
    py311-django{42,52},
    py312-django{42,52,60,main},
    py313-django{52,60,main},
    py314-django{52,60,main},

[testenv]
deps =
    django42: Django>=4.2.8,<4.3
    django52: Django>=5.2.8,<5.3
    django60: Django>=6.0,<6.1
    djangomain: https://github.com/django/django/archive/main.tar.gz
    pymemcache>=4.0,<5.0
    django-redis>=5.2,<6.0
    flake8

allowlist_externals =
    */run.sh

commands =
    ./run.sh test {posargs}
    ./run.sh flake8
